name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            preset: wx64-debug
            config: Debug
          - os: ubuntu-latest
            preset: lx64-debug
            config: Debug
          - os: windows-latest
            preset: wx64-release
            config: Release
          - os: ubuntu-latest
            preset: lx64-release
            config: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: '0'

      - name: Install Dependencies
        uses: ./.github/composite-actions/install-dependencies

      - name: Run CMake Build and Test
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.preset }}
          buildPreset: ${{ matrix.preset }}
          testPreset: ${{ matrix.preset }}